# generated by Neptune Namespaces v2.x.x
# file: Art/Ery/Elasticsearch/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Elasticsearch'
.addModules
  ElasticsearchConfig: require './ElasticsearchConfig'
require './Pipelines'