# generated by Neptune Namespaces v1.x.x
# file: Art/Ery/Elasticsearch/index.coffee

module.exports = require './namespace'
.addModules
  ElasticsearchConfig:   require './ElasticsearchConfig'  
  ElasticsearchPipeline: require './ElasticsearchPipeline'