# generated by Neptune Namespaces v2.x.x
# file: Art/Ery/Elasticsearch/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ElasticsearchConfig:           require './ElasticsearchConfig'          
  ElasticsearchPipeline:         require './ElasticsearchPipeline'        
  MirroredElasticsearchPipeline: require './MirroredElasticsearchPipeline'