# generated by Neptune Namespaces v2.x.x
# file: Art/Ery/Elasticsearch/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.Elasticsearch ||
Ery.addNamespace 'Elasticsearch', class Elasticsearch extends Neptune.Base
  ;
