# generated by Neptune Namespaces v2.x.x
# file: Art/Ery/Elasticsearch/Pipelines/namespace.coffee

Elasticsearch = require '../namespace'
module.exports = Elasticsearch.Pipelines ||
Elasticsearch.addNamespace 'Pipelines', class Pipelines extends Neptune.Base
  ;
