# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Ery/Elasticsearch/index.coffee

module.exports = require './namespace'
.addModules
  IndexEntry:  require './IndexEntry' 
  ParentChild: require './ParentChild'