# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Ery/Elasticsearch/index.coffee

module.exports = require './namespace'
.addModules
  GrandparentChild: require './GrandparentChild'
  IndexEntry:       require './IndexEntry'      
  ParentChild:      require './ParentChild'     