# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Ery/Elasticsearch/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ElasticsearchGlobal:           require './ElasticsearchGlobal'          
  GrandparentChild:              require './GrandparentChild'             
  Hashtags:                      require './Hashtags'                     
  IndexEntry:                    require './IndexEntry'                   
  MirroredElasticsearchPipeline: require './MirroredElasticsearchPipeline'
  ParentChild:                   require './ParentChild'                  