# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Ery/Elasticsearch/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.Elasticsearch ||
Ery.addNamespace 'Elasticsearch', class Elasticsearch extends Neptune.Base
  ;